
title: Bringing Ideas to Life Through Code
email: wmach73@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal portfolio! Here, you can explore more about my work, projects, and the skills I’ve developed as a web developer. Whether you're looking for collaboration, inspiration, or just curious about what I do, I'm glad you visited my site!

baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "hhtps://mac-hills.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  mac-hills

## Build settings
#theme: minima
#plugins:
#  - jekyll-feed
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - "*.scss"